# Generated by Django 3.1.1 on 2020-09-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorshy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Name',
        ),
        migrations.AddField(
            model_name='contact',
            name='Desc',
            field=models.TextField(default='fun', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='Email',
            field=models.EmailField(default='you@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
