# Generated by Django 3.1.1 on 2020-09-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorshy', '0003_auto_20200909_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Name',
            field=models.CharField(default='you', max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='Phone',
            field=models.IntegerField(default='0712456798'),
            preserve_default=False,
        ),
    ]
