# Generated by Django 3.1.1 on 2020-09-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorshy', '0005_auto_20200909_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Desc', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
